create table if not exists public.conversation_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  route text not null,
  ip_hash text,
  research_enabled boolean not null default false,
  access_state text not null default 'public_visitor',
  lead_submission_id bigint,
  invite_redemption_id bigint,
  admin_email text,
  request_context_json jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.conversation_sessions
  add column if not exists access_state text not null default 'public_visitor';

alter table public.conversation_sessions
  add column if not exists lead_submission_id bigint;

alter table public.conversation_sessions
  add column if not exists invite_redemption_id bigint;

alter table public.conversation_sessions
  add column if not exists admin_email text;

create index if not exists conversation_sessions_route_idx
  on public.conversation_sessions (route);

create table if not exists public.conversation_messages (
  id bigint generated by default as identity primary key,
  session_id text not null references public.conversation_sessions(session_id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  sources jsonb,
  research_used boolean not null default false,
  query_summary text,
  fetched_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists conversation_messages_session_idx
  on public.conversation_messages (session_id, created_at desc);

create table if not exists public.ai_operations (
  id bigint generated by default as identity primary key,
  session_id text not null references public.conversation_sessions(session_id) on delete cascade,
  route text not null,
  feature text not null check (feature in ('chat', 'research')),
  request_id text not null unique,
  response_id text,
  provider_request_id text,
  provider text not null,
  model text not null,
  gateway_used boolean not null default false,
  fallback_enabled boolean not null default false,
  fallback_used boolean not null default false,
  retry_count integer,
  transport_mode text not null,
  status text not null check (status in ('started', 'completed', 'failed')),
  error_phase text,
  error_message text,
  streamed_chars integer,
  request_context_json jsonb,
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_ms integer
);

create index if not exists ai_operations_session_idx
  on public.ai_operations (session_id, started_at desc);

create index if not exists ai_operations_route_idx
  on public.ai_operations (route, started_at desc);

create table if not exists public.ai_operation_events (
  id bigint generated by default as identity primary key,
  operation_id bigint not null references public.ai_operations(id) on delete cascade,
  event_type text not null,
  payload_json jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ai_operation_events_operation_idx
  on public.ai_operation_events (operation_id, created_at asc);

create table if not exists public.admin_allowlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lead_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  work_email text not null,
  company text not null,
  role_title text not null,
  session_id text,
  ip_hash text,
  status text not null default 'active',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists lead_submissions_email_idx
  on public.lead_submissions (work_email, created_at desc);

create index if not exists lead_submissions_session_idx
  on public.lead_submissions (session_id, created_at desc);

create table if not exists public.invite_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null unique,
  label text not null,
  status text not null default 'active',
  expires_at timestamptz,
  max_uses integer,
  current_uses integer not null default 0,
  created_by_email text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists invite_codes_status_idx
  on public.invite_codes (status, updated_at desc);

create table if not exists public.invite_redemptions (
  id bigint generated by default as identity primary key,
  invite_code_id bigint not null references public.invite_codes(id) on delete cascade,
  lead_submission_id bigint references public.lead_submissions(id) on delete set null,
  session_id text,
  ip_hash text,
  redeemed_at timestamptz not null default timezone('utc', now())
);

create index if not exists invite_redemptions_code_idx
  on public.invite_redemptions (invite_code_id, redeemed_at desc);

create index if not exists invite_redemptions_session_idx
  on public.invite_redemptions (session_id, redeemed_at desc);

create table if not exists public.app_settings (
  key text primary key,
  value_json jsonb not null,
  updated_by_email text,
  updated_at timestamptz not null default timezone('utc', now())
);
